FAIL ./yatze.test.ts
  Chance
    ✓ roll 5 dice (2 ms)
  Yatze
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully
  Ones
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully (1 ms)
  Twos
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Threes, Fours, Fives, Sixes
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully
  Pairs
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully
  Two Pairs
    ✕ roll 5 dice successfully (2 ms)
    ✓ roll 5 dice unsuccessfully (1 ms)

  ● Two Pairs › roll 5 dice successfully

    expect(received).toEqual(expected) // deep equality

    Expected: 10
    Received: 8

      66 |   it('roll 5 dice successfully', () => {
      67 |     expect(roll([1,1,2,3,3],"Two Pairs")).toEqual(8);
    > 68 |     expect(roll([1,2,2,3,3],"Two Pairs")).toEqual(10);
         |                                           ^
      69 |   })
      70 |       it('roll 5 dice unsuccessfully', () => {
      71 |     expect(roll([1,1,2,2,2],"Two Pairs")).toEqual(0);

      at Object.<anonymous> (yatze.test.ts:68:43)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 12 passed, 13 total
Snapshots:   0 total
Time:        2.77 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest --maxWorkers=2`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandbox/.npm/_logs/2025-05-05T07_46_56_241Z-debug.log
