FAIL ./yatze.test.ts
  Chance
    ✓ roll 5 dice (2 ms)
  Yatze
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Ones
    ✓ roll 5 dice successfully (2 ms)
    ✓ roll 5 dice unsuccessfully
  Twos
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully
  Threes, Fours, Fives, Sixes
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully
  Pairs
    ✕ roll 5 dice successfully (3 ms)
    ✓ roll 5 dice unsuccessfully (1 ms)

  ● Pairs › roll 5 dice successfully

    expect(received).toEqual(expected) // deep equality

    Expected: 8
    Received: 6

      55 | describe('Pairs', () => {
      56 |   it('roll 5 dice successfully', () => {
    > 57 |     expect(roll([3,3,3,4,4],"Pairs")).toEqual(8);
         |                                       ^
      58 |     expect(roll([1,1,6,2,6],"Pairs")).toEqual(12);
      59 |   })
      60 |       it('roll 5 dice unsuccessfully', () => {

      at Object.<anonymous> (yatze.test.ts:57:39)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 10 passed, 11 total
Snapshots:   0 total
Time:        2.68 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest --maxWorkers=2`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandbox/.npm/_logs/2025-05-05T07_37_00_178Z-debug.log
