FAIL ./yatze.test.ts
  Chance
    ✓ roll 5 dice (2 ms)
  Yatze
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully
  Ones
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully (1 ms)
  Twos
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Threes, Fours, Fives, Sixes
    ✓ roll 5 dice successfully (1 ms)
    ✓ roll 5 dice unsuccessfully (2 ms)
  Pairs
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully (1 ms)
  Two Pairs
    ✓ roll 5 dice successfully
    ✓ roll 5 dice unsuccessfully
  Three of a Kind
    ✕ roll 5 dice successfully (4 ms)

  ● Three of a Kind › roll 5 dice successfully

    expect(received).toEqual(expected) // deep equality

    Expected: 15
    Received: 9

      77 |   it('roll 5 dice successfully', () => {
      78 |     expect(roll([3,3,3,4,5],"Three of a Kind")).toEqual(9);
    > 79 |     expect(roll([3,5,5,4,5],"Three of a Kind")).toEqual(15);
         |                                                 ^
      80 |   })
      81 | //  it('roll 5 dice unsuccessfully', () => {
      82 | //    expect(roll([3,3,4,5,6],"Three of a Kind")).toEqual(0);

      at Object.<anonymous> (yatze.test.ts:79:49)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 13 passed, 14 total
Snapshots:   0 total
Time:        2.752 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test: `jest --maxWorkers=2`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sandbox/.npm/_logs/2025-05-05T07_52_31_311Z-debug.log
